Add table borders for legibility in richtext diary posts
openstreetmap/openstreetmap-website pull request #2959
Opened 2020-11-13 23:55 UTC by migurski

Introduce new table border treatment for richtext areas in diary entries. In diary entries with tables like [*Calculating label points with PostGIS*](https://www.openstreetmap.org/user/pnorman/diary/394676), [*2020 Editor Usage*](https://www.openstreetmap.org/user/Glassman/diary/394740), and [*Querying OpenStreetMap Changesets with Amazon Athena*](https://www.openstreetmap.org/user/Jennings%20Anderson/diary/394762) table elements appear squashed and hard to read.

This change slightly expands padding within table cell elements and adds thin, light-gray lines between rows and cells to make wider and more complex tables easier to read. Screenshots below are from Firefox 82.

### Current Site

<img width="453" alt="Screen Shot 2020-11-13 at 3 50 45 PM" src="https://user-images.githubusercontent.com/58730/99131442-ff7c7c00-25c7-11eb-91b1-44594009fc2b.png">

### This Change

<img width="453" alt="Screen Shot 2020-11-13 at 3 49 29 PM" src="https://user-images.githubusercontent.com/58730/99131379-d360fb00-25c7-11eb-8747-156a06b68041.png">

2020-11-18 15:58 UTC, gravitystorm requested changes
Thanks for the PR. I'm happy to see more styling being added to tables within diary entries and other places where we have our "richtext" content.

However, we need to change the approach used. We've moved to Bootstrap for most of our styling, and so we should not be adding more custom styling rules to common.scss any longer. Bootstrap gives us various table styling options (https://getbootstrap.com/docs/4.5/content/tables/) out of the box, and so we should use one of them.

Since bootstrap tables are opt-in, i.e. require a class to be added to the `<table>` tag, then that will need to be implemented as part of the RichText.to_html process (in [`lib/rich_text.rb`](https://github.com/openstreetmap/openstreetmap-website/blob/4e78f3ae5b0d96f599840e181c1a4be4335dded9/lib/rich_text.rb))

2020-11-18 18:09 UTC, migurski commented
Thanks Andy. I’ll see if that ERB change is something I can make.

(Aside: I’ve mostly found Ruby really hard to deal with from a systems/installation perspective. I’ve been able to make and test small changes like this due to the Docker support in #2409 that @jalessio implemented. I’ve been keeping that PR updated but it’s been in limbo for over a year. I would love to see it merged and supported in order to allow other non-Ruby developers like myself to propose small changes)

2020-11-19 05:43 UTC, migurski commented
I’ve backed out the custom CSS and applied Bootstrap table styles instead:

<img width="346" alt="Screen Shot 2020-11-18 at 9 39 36 PM" src="https://user-images.githubusercontent.com/58730/99626208-90978c80-29e6-11eb-8c80-d1c8154e4fa4.png">

2020-11-19 09:58 UTC, tomhughes commented
Thanks for the idea and the proof of concept @migurski but I'm not hugely keen on editing the generated HTML so I've opened #2971 as an alternative implementation that works by overriding the kramdown converter to add the classes as the HTML is generated.

2020-11-19 15:04 UTC, closed without merging