Add last updated date to diary entry page
openstreetmap/openstreetmap-website pull request #2969
Opened 2020-11-18 01:51 UTC by tuckerrc

Resolves #2801

2020-11-25 13:29 UTC, gravitystorm requested changes

2020-11-25 13:29 UTC, gravitystorm commented on config/locales/en.yml
> +      posted_by_html: "Posted by %{link_user} on %{created} in %{language_link} last updated on %{updated}"
Unfortunately we can't change the number of interpolation variables in an existing string. Doing so causes server errors until all the translation strings are updated. So if you change the number of interpolation variables, you have to also rename the translation key (`posted_by_html`). 

Alternatively, you could look at adding this as a separate sentence, i.e. adding a full stop to the existing sentence, and starting a new one with the last updated information.

2020-11-27 03:07 UTC, tuckerrc commented on app/views/diary_entries/_diary_entry.html.erb
> +      <%= t(".posted_by_html", :link_user => (link_to diary_entry.user.display_name, user_path(diary_entry.user)), :created => l(diary_entry.created_at, :format => :blog), :language_link => (link_to
I was going for simple code changes but I like this idea better. I created a new string and made it conditional.

2020-12-02 11:30 UTC, gravitystorm approved these changes

2020-12-02 11:30 UTC, merged

2020-12-02 11:30 UTC, gravitystorm commented
Great, thanks for making the changes!