Dittaeva ancient patch
openstreetmap/openstreetmap-website pull request #3536
Opened 2022-04-25 02:14 UTC by JesseWeinstein

I've fixed the merge conflicts for this ancient PR; it seems like the name corrections are still helpful.

2022-04-25 08:33 UTC, dittaeva commented
Thanks Jesse! I remember doing the patch, and it is really nice that it finally is put to use.

2022-04-27 13:30 UTC, gravitystorm requested changes
I'm generally happy with the PR, and neutral on most of the changes, but I've flagged a few that need further attention.

2022-04-27 13:30 UTC, gravitystorm commented on config/locales/en.yml
> +          fast_food: "Fast Food Restaurant"
This should be removed, since amenity=fast_food also covers food trucks and takeaway only outlets.

2022-04-27 13:30 UTC, gravitystorm commented on config/locales/en.yml
> +          farm: "Farmland"
This key is deprecated and should be removed rather than changed. There's only a few instances of it remaining in the database in 2022 anyway.

2022-04-27 13:30 UTC, gravitystorm commented on config/locales/en.yml
> +          dry_cleaning: "Dry Cleaner"
The "Dry cleaning" term is the one exclusively used in the OSM wiki, so I think it's fine to keep the original

2022-04-27 14:15 UTC, JesseWeinstein commented
Reverted the four that you flagged (thanks)! Let me know if there are any other changes requested.

2022-04-27 15:19 UTC, gravitystorm approved these changes

2022-04-27 15:29 UTC, merged