Use $.ajax instead of iframe to make remote control requests
openstreetmap/openstreetmap-website pull request #3760
Opened 2022-10-20 12:42 UTC by AntonKhorev

iframe with src set to remote control request urls first appeared in https://github.com/openstreetmap/openstreetmap-website/commit/c3453cf57df864b008dca6479f84504f81c0b131 and was updated with timeout alert in https://github.com/openstreetmap/openstreetmap-website/commit/d4135390acff291f2f2c15d9fb86723ebf4fe755.

jQuery's $.ajax can make the same requests and has builtin timeout support.

2022-10-23 17:29 UTC, tomhughes commented
I can't remember the details but there were very good reasons it was done with an iframe... Maybe things have moved on and it's no longer necessary but it would be good to know what the original reasoning was if anybody can remember.

2022-10-24 08:56 UTC, AntonKhorev commented
The most likely reason is this one described [here](https://josm.openstreetmap.de/wiki/Help/RemoteControlCommands#version):
"For older browsers not implementing [​Cross-Origin Resource Sharing (CORS)](http://en.wikipedia.org/wiki/Cross-Origin_Resource_Sharing)...". Basically for compatibility with really old browsers that weren't as old in 2010 when this code was written.

Changing `src` on elements is a way of making a GET request without caring whether you have the permissions to read its response when you don't care about the response. JOSM just sends back "OK" on success.

2022-10-24 09:03 UTC, tomhughes commented
Right, but even with CORS the editor will need to send back an `Access-Control-Allow-Origin` header for AJAX to work right? Do all the editors do that?

2022-10-24 09:03 UTC, tomhughes commented
Maybe that's not required for localhost in modern browsers though? But how modern?

2022-10-24 09:42 UTC, AntonKhorev commented
You're doing cross-domain requests with $.ajax() since at least 2014 for overpass searches.

2022-10-24 12:34 UTC, AntonKhorev commented
- JOSM sends `Access-Control-Allow-Origin`
- Merkaartor [also sends it](https://github.com/openstreetmap/merkaartor/blob/7ae76834bcba9934f38d85058f7372fc016c1d1c/src/Utils/RemoteControlServer.cpp#L72).
- Potlatch doesn't

2022-10-24 12:50 UTC, AntonKhorev commented
Without `Access-Control-Allow-Origin` the rc command will still work but the browser will think that it failed.

2022-10-25 11:01 UTC, AntonKhorev commented
In modern browsers it's possible to do [no-cors fetch](https://developer.mozilla.org/en-US/docs/Web/API/Request/mode#no-cors) instead of adding hidden elements and altering their src:

```
fetch(url, { mode: "no-cors" })
```

2022-10-25 11:14 UTC, tomhughes commented
I haven't had much luck figuring out how new exactly a browser has to be to support that but it's been in the specification (under that name) since [2014](https://github.com/whatwg/fetch/commit/37a50bc53b13ce84b92281f2aa2811c69f909710) so I'm guessing it should be reasonably well supported by now.

2022-10-25 11:30 UTC, AntonKhorev commented
I'm not completely sure about Safari:
https://caniuse.com/?search=Sec-Fetch-Mode

2022-10-25 11:40 UTC, tomhughes commented
You don't actually need that for XHR to support it though, as the XHR support is client side - whether it chooses to abort or return the limited access response when there is no CORS response header.

2022-12-04 20:45 UTC, mmd-osm commented
I believe using `$.ajax` should be fine here. I don't see much reason to spend time on the Potlatch 3 topic, though. These users are probably used to the error popup. When switching to $.ajax, nothing will change for them.

Maybe you could open an issue on https://github.com/systemed/potlatch3 and discuss adding an "Access-Control-Allow-Origin" header somewhere around here: https://github.com/systemed/potlatch3/blob/master/com/airhttp/ActionController.as#L149-L174

2022-12-06 13:23 UTC, AntonKhorev commented
> These users are probably used to the error popup.

What is the error popup they are used to? Without this PR there's no CORS error.

2022-12-06 13:51 UTC, mmd-osm commented
I tested Potlatch 3 remote control on osm.org, which shows the error popup.

2022-12-06 14:02 UTC, AntonKhorev commented
> I tested Potlatch 3 remote control on osm.org, which shows the error popup.

When launching it from a note page or from any page?

2022-12-06 14:04 UTC, mmd-osm commented
I didn't use the note page. Just plain remote edit.

2022-12-06 14:18 UTC, AntonKhorev commented
I don't get any error popups.

You may get one if the request takes more than 5 seconds. Actually I increased it from one second when I added the second request to note pages. With just one second I was sometimes getting the popup even when using josm.

2022-12-06 14:20 UTC, mmd-osm commented
I think potlatch 3 immediately loaded the respective area, I don't see where a delay should come from. It's not like JOSM where you might have to accept the remote call depending on configuration.

2022-12-06 18:23 UTC, mmd-osm commented
I tried it again today, still on Ubuntu 22.04, but I cannot reproduce the error popup at this time. 🤷

2022-12-06 19:26 UTC, tomhughes commented
To be clear are you talking about testing Potlatch 3 with the current site? or with this PR merged?

Before I merge this is there any good reason not to add the `mode: "no-cors"` change? What would happen with that if somebody was somehow using a browser that didn't understand it? Would it fail or would it just behave as it would without that and do a CORS fetch?

2022-12-06 19:35 UTC, mmd-osm commented
So with this pull request in place, I'm getting:

![grafik](https://user-images.githubusercontent.com/5842757/206005163-8d889fb9-11e9-47d1-8dc3-636ec849cee6.png)

I also tested the current site yesterday, and thought I saw the same popup. Upon retesting this today, I don't see the timeout popup anymore. Most likely, I mixed up the master branch and this pull requests in my local install at one point.

2022-12-06 20:47 UTC, mmd-osm commented
Unfortunately, that didn't work, I'm getting the same "Editing failed" popup as above.

By the way, you can also simulate what Potlatch is sending by running:

```
echo -e "HTTP/1.1 200 OK\\nContent-Type: text/plain\\n\\nOK" | netcat -q 1 -l -p 8111
```

(includes a delay of 1s)

2022-12-07 19:05 UTC, tomhughes requested changes
The reason this is erroring is not because of CORS it's because the CSP is not allowing the XHR fetches - the rules at https://github.com/openstreetmap/openstreetmap-website/blob/master/app/controllers/application_controller.rb#L289 need to be changed to move the 127.0.0.1 rules from `child_src` and `frame_src` to `connect_src`.

2022-12-14 11:40 UTC, systemed commented
> Maybe you could open an issue on https://github.com/systemed/potlatch3 and discuss adding an "Access-Control-Allow-Origin" header somewhere around here: https://github.com/systemed/potlatch3/blob/master/com/airhttp/ActionController.as#L149-L174

Yes, I think that'd work. I'll probably do a new release of P3 in the New Year so it'd be good to have a steer before then if this is going to happen.

2022-12-18 19:58 UTC, mmd-osm commented
> The reason this is erroring is not because of CORS it's because the CSP is not allowing the XHR fetches

I tried this today without much luck. It seems we would still need the Access-Control-Allow-Origin header to get rid of the error message.

2024-07-28 19:44 UTC, simonpoole commented
Does anybody happen to have an instance with these changes running somewhere? Maybe the change would make https://github.com/openstreetmap/openstreetmap-website/pull/1478 superfluous as the main reason for the complications was the iframe use, so it would be nice to test Vespucci against it.

2024-07-28 21:06 UTC, HolgerJeromin commented
My personal feeling would to avoid jQuery for this.
jQuery is a wrapper which does funny stuff sometimes.

Do the same as jQuery does which gives more control (and is more stable with jQuery updates).

2024-07-28 21:47 UTC, tomhughes commented
Well my personal preference would be to use it because it's what all the rest of our code does so unless you have an actual concrete reason not to use it rather than vague accusations then I think I win.

2024-07-30 13:40 UTC, HolgerJeromin commented
Funny stuff example:
https://github.com/jquery/jquery/issues/4145
But you are right. My single-page application has different problems with it than this website (for which jQuery was designed for).

2024-07-30 16:09 UTC, AntonKhorev commented
> Funny stuff example: [jquery/jquery#4145](https://github.com/jquery/jquery/issues/4145)

What does it have to do with `$.ajax`?

2024-12-04 09:09 UTC, AntonKhorev commented
Moved "http://127.0.0.1:8111" to `connect_src` which should fix CSP errors.

Did nothing about CORS because looks like jQuery doesn't support no-cors mode. But that shouldn't stop the request from working.

2024-12-08 14:59 UTC, tomhughes commented
Superseded by #5375.

2024-12-08 14:59 UTC, closed without merging