Make "Load more" button on history pages work as a link to the next page
openstreetmap/openstreetmap-website pull request #3829
Opened 2022-12-07 16:04 UTC by AntonKhorev

"Pagination working properly without javascript" from https://github.com/openstreetmap/openstreetmap-website/issues/647#issuecomment-1298624196.

The link actually exists even without this PR. You can open any changeset list page, middle-click the "Load more" button and you'll get the next page but it won't have the correct layout.

This PR makes the link work as a proper webpage. Also it changes the link from `.../history?max_id=(id)` to `.../history/(id)`. This makes it possible to construct permalinks to some point in time of someone's edit history.

The plan is later to update the id in the url when the sidebar is scrolled, similar to how [the new forum](https://community.openstreetmap.org/) updates its urls with comment numbers. This would roughly do what was requested in https://github.com/openstreetmap/openstreetmap-website/issues/933. Also it would do https://github.com/openstreetmap/openstreetmap-website/issues/647 but without caching.

Smaller parts of this PR:

- [ ] https://github.com/openstreetmap/openstreetmap-website/pull/3834
- [ ] https://github.com/openstreetmap/openstreetmap-website/pull/3835

2022-12-09 17:45 UTC, tomhughes requested changes

2022-12-09 17:45 UTC, tomhughes commented on app/assets/javascripts/index/history.js
> +    loadFirstChangesets(maxId);
I don't understand the point of this, indeed of any of this commit, when you remove it all again in the next commit?

2022-12-09 17:45 UTC, tomhughes commented on app/views/changesets/index.html.erb
> +    <%= link_to t(".load_more"), "#{url_for}/#{@changesets.last.id - 1}", :class => "btn btn-primary" %>
That way of constructing the URL is not a good idea - doesn't `url_for(:max_id => @changesets.last.id - 1)` work? If not then there will something which does and which doesn't rely on manually gluing the component together like that.

2025-04-02 05:50 UTC, AntonKhorev commented
Superseded by #5876

2025-04-02 05:50 UTC, closed without merging