Use flex container instead of floats in header
openstreetmap/openstreetmap-website pull request #4296
Opened 2023-10-18 10:07 UTC by AntonKhorev

This is a step towards [Bootstrap navbar](https://getbootstrap.com/docs/5.2/components/navbar/), which also uses flex.

You don't want floats there because https://github.com/openstreetmap/openstreetmap-website/issues/3433#issuecomment-1632814133 too and they don't make sense anyway when flex is widely available in browsers.

Fixes #2536 if it was caused by line breaks when measuring widths.

2023-11-15 16:03 UTC, gravitystorm requested changes
Thanks @AntonKhorev , I definitely want to get rid of all of the floats.

However, in this PR the menus aren't working for me when I change the window size. For example, everything is fine at wide screen widths:

![Screen Shot 2023-11-15 at 15 51 45](https://github.com/openstreetmap/openstreetmap-website/assets/360803/5d52070d-98bf-43ba-bd8a-3f8ecad5d32c)

Then as the screen is narrowed there is a positioning error:

![Screen Shot 2023-11-15 at 15 52 05](https://github.com/openstreetmap/openstreetmap-website/assets/360803/5de3e368-268b-4272-993b-6a0f98206f72)

Then slightly narrower it looks OK again:

![Screen Shot 2023-11-15 at 15 52 10](https://github.com/openstreetmap/openstreetmap-website/assets/360803/1fdf5d23-37a3-481f-9f99-1d598ac41041)

Then during the next transition there is also an error:

![Screen Shot 2023-11-15 at 15 52 16](https://github.com/openstreetmap/openstreetmap-website/assets/360803/e3cb11f7-c53d-4916-ae99-5a71377a498d)

Then it looks OK again:

![Screen Shot 2023-11-15 at 15 52 23](https://github.com/openstreetmap/openstreetmap-website/assets/360803/ceb8718a-d1ec-412e-8fb2-dcc1827e4252)

Other notes:
* The same errors are shown as the width increases (vs decreases)
* The same errors are shown when refreshing the page at the given error width
* UA: Firefox 119.0.1 (Ubuntu)
* If there's some way to avoid the absolute positioning (of the menu icon in small-nav mode) that would be great. Perhaps it can be positioned using flex too?

2023-11-16 10:55 UTC, AntonKhorev commented
Seems to be related to an avatar image.

2023-11-17 09:50 UTC, AntonKhorev commented
Changed user thumbnail to always be 25x25 px instead of width: auto, should help with width calculations.

2023-11-17 09:59 UTC, AntonKhorev commented
> If there's some way to avoid the absolute positioning (of the menu icon in small-nav mode) that would be great.

This is temporary if the end goal is [Bootstrap navbar](https://getbootstrap.com/docs/5.3/components/navbar/). It has its own menu button.

2023-11-22 17:22 UTC, gravitystorm approved these changes
Looks good to me, thanks!

2023-11-22 17:22 UTC, merged