Use .icon-link to align logo
openstreetmap/openstreetmap-website pull request #4823
Opened 2024-05-21 17:47 UTC by AntonKhorev

Removes pixel sizes specific to the logo.

`.icon-link` also makes the gap between the logo and "OpenStreetMap" slightly bigger:
![image](https://github.com/openstreetmap/openstreetmap-website/assets/4158490/631bcbb3-6769-4867-a68a-2683b0e3b39f)
![image](https://github.com/openstreetmap/openstreetmap-website/assets/4158490/e7fc94e3-21dc-4285-af73-939f3bdd1c0b)

2024-05-21 17:58 UTC, tomhughes requested changes
This causes the text part of the logo to get a link underline when hovered, which it didn't have before... The text also moves down slightly relative to the icon which I'm not sure about - the alignment looks slightly worse to me?

2024-05-21 22:05 UTC, AntonKhorev commented
Does it really move down?

![image](https://github.com/openstreetmap/openstreetmap-website/assets/4158490/4bca316e-1559-4706-8f4c-1545bf26cbdf) ![image](https://github.com/openstreetmap/openstreetmap-website/assets/4158490/77bc4f33-b5ce-43f4-b413-d229e94e7a0e)

![image](https://github.com/openstreetmap/openstreetmap-website/assets/4158490/d350a224-17e1-4df9-a346-39ea091e5aa7)

2024-05-21 22:16 UTC, AntonKhorev commented
Restored the original horizontal gap:
![image](https://github.com/openstreetmap/openstreetmap-website/assets/4158490/a90f666d-42b9-490e-8acc-e4b25ffb978a)
![image](https://github.com/openstreetmap/openstreetmap-website/assets/4158490/e239908c-c85f-4562-b11e-35d8213e5fb2)

2024-05-22 17:45 UTC, tomhughes approved these changes
There definitely is a slight movement vertically - if you have the old and new versions open in two tabs and flip back and forth you can see it. I don't think it's enough to worry about though.

2024-05-22 17:45 UTC, merged