Fixed "Tab alignment" issue described in #4773
openstreetmap/openstreetmap-website pull request #4826
Opened 2024-05-23 14:55 UTC by nenad-vujicic

This PR addresses "Tab alignment" issue mentioned in the #4773. I removed px-3 class from <ul> tag defining area in which are "Log in" and "Sign up" tabs.

2024-05-23 15:33 UTC, AntonKhorev commented
`px-3` also on the `/user/new` page.

2024-05-23 17:24 UTC, tomhughes requested changes
As @AntonKhorev pointed out this needs to be done for the signup page as well or the tabs will move as you switch between the two.

2024-05-24 09:59 UTC, nenad-vujicic commented
Dear @AntonKhorev, @tomhughes ,

Thanks for reviewing! I apologize for non-complete testing first time. Now, both tabs will be aligned.

Please, let me know if you find another place which could be improved.

Thanks,
Nenad.

2024-05-24 10:11 UTC, tomhughes requested changes
That's fine now thanks, but there's no need for a separate commit. If you can just squash that into the first commit then I'll merge it.

2024-05-24 10:48 UTC, nenad-vujicic commented
Dear @tomhughes,

They are squashed now into the first commit. Thank you very much!

Thanks,
Nenad.

2024-05-24 11:02 UTC, merged

2024-05-24 11:02 UTC, tomhughes commented
Thanks - that is merged now.