Fixed "or divider" issue described in #4773
openstreetmap/openstreetmap-website pull request #4857
Opened 2024-05-29 09:53 UTC by nenad-vujicic

This PR addresses "or divider" issue mentioned in the #4773

In app\views\sessions\new.html.erb and app\views\users\new.html.erb added mb-2 after "or" divider.

Before:
![image](https://github.com/openstreetmap/openstreetmap-website/assets/25298521/661d532e-db21-45f7-87b0-54b6e8c28c7c)
After:
![image](https://github.com/openstreetmap/openstreetmap-website/assets/25298521/dc84e1a5-3cad-4ca8-a90f-48f2ef83dab4)

2024-05-29 16:58 UTC, tomhughes requested changes
This moves the line relative to the `or` text so the line is more or less aligned with the bottom of the text but I think it's better when the line is aligned with the middle of the text? I don't think the old version quite has them perfectly middle aligned but it's certainly a lot closer than this.

2024-05-29 16:58 UTC, tomhughes commented on app/views/sessions/new.html.erb
> +      <div class="text-secondary mx-3 mb-2"><%= t ".or" %></div>
Was there a reason for choosing the `mb-2` rather than `mb-3` that @gravitystorm suggested?

2024-05-30 10:29 UTC, nenad-vujicic commented
Dear @tomhughes ,

Regarding using mb-2 vs mb-3 .. When looking at distances between "Log in with Microsoft" and dividing line and dividing line and "Email Address and Username", they look more similar when using mb-2 than when using mb-3. Please, take a look at below screenshots (I can quickly switch to mb-3 if you prefer?):

mb-2:
![image](https://github.com/openstreetmap/openstreetmap-website/assets/25298521/105ad5b9-546e-4d9c-a031-a76e93151b0d)
mb-3:
![image](https://github.com/openstreetmap/openstreetmap-website/assets/25298521/99b06365-3db2-4fde-b126-376ab6fdcd58)

Regarding problems with aligning lines with the middle of the "or" text .. I moved mb-2 to upper div, and this returned us to previous alignment. The problem with making this alignment perfect is browser's layout manager uses bounding box of uppercase of the "or" label, not the lowercase (doesn't respect kerning properties). I can fix it by setting a margin, but it will create a problem again if user selects a language with big glyphs (?locale=kn, ..) or switch to uppercase "OR", but it wouldn't look so nice again .. Please, let me know if you have any other idea?

Btw, I'm constantly getting for one- or two-lines changes failing checks (yesterday, Docker, today, Tests / Ubuntu ... Ruby 3.0). Do you have ideas why do they happen or how to mitigate them?

Thanks,
Nenad.

2024-05-30 10:35 UTC, gravitystorm commented
> Btw, I'm constantly getting for one- or two-lines changes failing checks (yesterday, Docker, today, Tests / Ubuntu ... Ruby 3.0). Do you have ideas why do they happen or how to mitigate them?

In this case it just had one job as "cancelled" and I don't know why that happened. I've re-run the failed jobs now (it's not clear to me how many people have permission to re-run failed tests).

Let us know if it happens in future. Usually jobs fail with a more obvious error message.

2024-05-30 10:49 UTC, nenad-vujicic commented
> > Btw, I'm constantly getting for one- or two-lines changes failing checks (yesterday, Docker, today, Tests / Ubuntu ... Ruby 3.0). Do you have ideas why do they happen or how to mitigate them?
> 
> In this case it just had one job as "cancelled" and I don't know why that happened. I've re-run the failed jobs now (it's not clear to me how many people have permission to re-run failed tests).
> 
> Let us know if it happens in future. Usually jobs fail with a more obvious error message.

Great, thanks! Now it passed all checks!

Thanks,
Nenad.

2024-05-30 15:25 UTC, tomhughes approved these changes
Thanks, that looks much better now. I realise exactly centring the text and line is hard - as it happens I was reading https://tonsky.me/blog/centering/ last night which has more detail than you could ever hope for...

2024-05-30 15:26 UTC, merged