Show changeset element counts using badges
openstreetmap/openstreetmap-website pull request #4872
Opened 2024-06-03 12:10 UTC by AntonKhorev

We use counter badges in other places. We can use them on changeset pages in element headings instead of numbers in ().

![image](https://github.com/openstreetmap/openstreetmap-website/assets/4158490/55a2742a-b978-4873-8e00-a5a6eb8d4a0c) ![image](https://github.com/openstreetmap/openstreetmap-website/assets/4158490/eab29825-edcb-44c2-8096-9689434d6c29)

2024-08-29 11:48 UTC, nenad-vujicic requested changes
This looks and works great, thanks for it! Requires updating with the latest changes of _paging_nav.html.erb / en.yml.

2024-08-29 14:28 UTC, AntonKhorev commented
rebased

2024-08-29 19:38 UTC, nenad-vujicic approved these changes
It looks and works perfectly now, thank you very much!

2025-03-21 09:33 UTC, hlfan commented on config/locales/en.yml
> +      range: "%{x}-%{y} of %{count}"
Why can't the `*_paginated` translations be removed?

2025-03-21 09:41 UTC, hlfan commented on app/views/changesets/_paging_nav.html.erb
> +
I'd find a duplicated if easier to read than a duplicated h4.
```suggestion
  <h4 class="fs-5">
    <%= t ".#{type.pluralize}_title" %>
    <span class="badge count-number">
      <%= if pages.page_count == 1
            pages.item_count
          elsif pages.page_count > 1
            t(".range", x: pages.current_page.first_item,
                        y: pages.current_page.last_item,
                        count: pages.item_count)
          end %>
    </span>
  </h4>
<% if pages.page_count > 1 %>
```

2025-03-25 14:19 UTC, AntonKhorev commented on config/locales/en.yml
> +      range: "%{x}-%{y} of %{count}"
Search for `_paginated` to see where they are used.

2025-03-25 14:32 UTC, AntonKhorev commented on app/views/changesets/_paging_nav.html.erb
> +
This is reproducing what I removed from `browse_helper.rb`, except as a code block inside the template.

2025-03-25 19:16 UTC, tomhughes commented
Looks good to me, thanks.

2025-03-25 19:17 UTC, merged