style auth buttons using .btn & .btn-light classes
openstreetmap/openstreetmap-website pull request #4916
Opened 2024-06-21 12:22 UTC by kcne

This PR addresses [#4455](https://github.com/openstreetmap/openstreetmap-website/issues/4773) issues discussion regarding auth_button_preferred css classes section. Auth anchor tags now use button styles as base style which will enforce consistency with other buttons.

2024-06-21 18:19 UTC, tomhughes requested changes
That discussion is about the preferred button on the left (the one with the button style outline) which this PR doesn't actually seem to change? I don't have a problem with also doing the ones on the right but the preferred provider one needs to be done as well.

2024-06-27 14:39 UTC, kcne commented
Preferred auth button has been updated as well. Could you please check if everything looks okay?
@tomhughes

2024-06-27 14:40 UTC, kcne commented
<img width="688" alt="Screenshot 2024-06-27 at 16 39 43" src="https://github.com/openstreetmap/openstreetmap-website/assets/76796906/4be250ce-5da7-4185-a822-a4ed6421b135">
<img width="765" alt="Screenshot 2024-06-27 at 16 39 58" src="https://github.com/openstreetmap/openstreetmap-website/assets/76796906/6377fc3f-5e96-4260-84da-5c6fd3da99d4">

2024-06-27 16:58 UTC, tomhughes approved these changes
That looks good to me now, thanks.

2024-06-27 17:04 UTC, merged