When downloading image by "Share", allow other map styles with static image APIs
openstreetmap/openstreetmap-website pull request #4973
Opened 2024-07-10 11:20 UTC by nertc

This PR addresses "When downloading image by 'Share', allow other map styles with static image APIs" issue mentioned in the https://github.com/openstreetmap/openstreetmap-website/issues/1886

Added API for downloading Transport and Cycle Map images, as they are supported by the [ThunderForest](https://www.thunderforest.com/docs/static-maps-api/). Also changed unsupported map text to show that not only Standard, but Transport and Cycle Map layers also have downloading capability. Fixes https://github.com/openstreetmap/openstreetmap-website/issues/1886

Transport layer:
![Screenshot 2024-07-10 140949](https://github.com/openstreetmap/openstreetmap-website/assets/55288419/6ebd6d04-026e-4ef1-81cf-cbc6a3dcc6ab)

Cycle Map layer:
![Screenshot 2024-07-10 141009](https://github.com/openstreetmap/openstreetmap-website/assets/55288419/022bb17a-35f8-4619-af1c-be6f3697066d)

Unsupported Humanitarian layer:
![Screenshot 2024-07-10 141024](https://github.com/openstreetmap/openstreetmap-website/assets/55288419/98c9ae8a-f93d-4a3f-b075-a05bf8be6c9b)

2024-07-10 12:04 UTC, tomhughes commented
Have we confirmed with @gravitystorm that he's happy for us to do this? We have to take pretty extreme measures to protect our infrastructure from abuse of this facility so load may be a concern but I don't know exactly how his static map endpoint works.

2024-07-11 14:47 UTC, nertc commented
Hello @gravitystorm, I am interested what do you think about this issue. When user will download an image with Cycle Map or Transport layer, it will call `https://tile.thunderforest.com/static/{style}/{lon},{lat},{zoom}/{width}x{height}{scale}.{format}?apikey={apikey}` as indicated on [Thunderfores - Static Maps API](https://www.thunderforest.com/docs/static-maps-api/). Image generation requires one api call. ApiKey is the same as in the tiles request. In terms of security, API key is shown as query parameter both in tiles and image generation requests.

2024-07-12 03:32 UTC, pnorman commented
We obviously should get Andy's okay, but a vector tile based static map endpoint is at least a couple of orders of magnitude more efficient than ours which does DB queries on demand.

2024-07-12 08:15 UTC, gravitystorm commented
> Hello @gravitystorm, I am interested what do you think about this issue.

I'm happy on behalf of Thunderforest for this to be implemented. As @pnorman says, it's much less resource intensive on our infrastructure than the approach used by OSMF for the standard map layer. And if there's any unforeseen problems, then I'm happy to revisit this later.

(As a maintainer here, I haven't reviewed the PR!)

2024-07-14 14:54 UTC, tomhughes requested changes
There's a message (from the `javascripts.share.image_dimensions` key) that appears before the download button and which currently says the image will be of the standard layer which is no longer true.

I think that dates from before we started hiding image export on other layers and the reference to the layer can probably be removed now.

2024-07-15 15:24 UTC, nertc commented
@tomhughes Thanks for the review. I changed the key so it will show `Image will show %{layer} layer at %{width} x %{height}` appropriate layer.

Transport Map layer example:
Image will show Transport Map layer at 1522 x 1464
![Screenshot 2024-07-15 192120](https://github.com/user-attachments/assets/101d6dd6-0a70-4599-989d-c368fc83a43e)

2024-07-16 16:23 UTC, tomhughes approved these changes
Thanks - that looks good now.

2024-07-16 16:36 UTC, merged