Allows sending follow-ups to sent messages
openstreetmap/openstreetmap-website pull request #5120
Opened 2024-08-26 15:45 UTC by nenad-vujicic

PR adds Reply button when displaying sent messages, so users can send follow-ups
 
Fixes 3497. Adds Reply button when displaying sent messages (app/views/messages/show.html.erb) and allows replying to messages for which sender is current user (app/controllers/messages_controller.rb).

![image](https://github.com/user-attachments/assets/71ad4e45-cfa7-4b70-bccd-002ce42f1a2c)

2024-08-27 11:14 UTC, nertc commented
Functionality works perfectly. I think, it also fixes https://github.com/openstreetmap/openstreetmap-website/issues/2644. Despite of the fact, that it implements a different solution (reply instead of forward), there won't be a problem stated in the issue. 
Also, shouldn't there be a test for checking redirection and rendering of the reply button in outbox items?

2024-08-27 18:15 UTC, tomhughes requested changes
This looks good to me if we could just add some tests as @nertc suggests?

2024-08-28 13:36 UTC, nenad-vujicic commented
Improved tests, thanks!

2024-08-28 17:31 UTC, tomhughes approved these changes
That looks good now, thanks.

2024-08-28 17:41 UTC, merged