Displays links for friend options on user profile only if user is signed in
openstreetmap/openstreetmap-website pull request #5203
Opened 2024-09-12 11:58 UTC by nenad-vujicic

PR proposes displaying "Send Message", "Add Friend" and "Unfriend" links (buttons) on user profile page only if user is signed in. Previously, these links (buttons) were always displayed.

Fixes #5199 

Signed In:
![image](https://github.com/user-attachments/assets/9456879b-e3f7-4cc6-8706-43685f8f7cc0)

Signed Out:
![image](https://github.com/user-attachments/assets/8e65cd0c-eb62-4d18-84b5-ae01d6b7f495)

2024-09-14 10:15 UTC, tomhughes requested changes
I think we should definitely remove add/remove friend as they can't be correctly rendered without knowing the current friendship state but I think we should probably leave send message as it's reasonable to offer to everybody, even those that would have to signup to send a message.

2024-09-14 16:35 UTC, kcne approved these changes

2024-09-14 21:33 UTC, nenad-vujicic commented
> I think we should definitely remove add/remove friend as they can't be correctly rendered without knowing the current friendship state but I think we should probably leave send message as it's reasonable to offer to everybody, even those that would have to signup to send a message.

Thanks, updated. Here are the latest screenshots:

Logged-in:
![image](https://github.com/user-attachments/assets/188a27af-d718-45bd-bd4b-f23f8ce6df81)

Logged-out:
![image](https://github.com/user-attachments/assets/352ffa28-c703-4a09-89cc-a0b7944a3e9d)

2024-09-15 18:30 UTC, tomhughes approved these changes
Thanks - that looks good now.

2024-09-15 18:33 UTC, merged