Put api keys directly in js layer definitions
openstreetmap/openstreetmap-website pull request #5352
Opened 2024-11-23 22:59 UTC by AntonKhorev

Currently map layer API keys have one extra level of indirection:
- keys are defined in the settings
- `osm.js.erb` reads them from the settings and writes them to `OSM.THUNDERFOREST_KEY` and `OSM.TRACESTRACK_KEY`
- `layers.yml` contain names of `OSM` properties to check for keys

Instead of this `osm.js.erb` could write keys directly to layer definitions, skipping `OSM.THUNDERFOREST_KEY` and `OSM.TRACESTRACK_KEY`. `layers.yml` could contain the corresponding settings names. The advantage is that Thunderforest and Tracestrack keys are no longer special. A new key can be added just by editing `settings.yml` and `layers.yml`. Also it's possible to skip layer definitions if they require a key and that key is missing.

2024-11-24 16:00 UTC, AntonKhorev commented
I moved that ruby code to a module, but now there's no dependency on it. If it's changed, `osm.js` won't be recompiled.

2025-02-04 18:05 UTC, hlfan requested changes

2025-02-04 18:05 UTC, hlfan commented on config/layers.yml
> +  apiKeyId: "thunderforest_key"
Now that this is used in embed.js.erb as well, that file would need to be accommodated too.

2025-02-10 19:04 UTC, tomhughes requested changes
As @hlfan says this will need modifying to support `embed.js.erb` now - possibly the block of ruby code there should become an extra method in the `MapLayers` library that this introduces?

2025-02-10 19:33 UTC, hlfan commented
Maybe something along the lines of this?
```ruby
def self.embedDefinitions(layers_filename)
  self.definitions(layers_filename)
    .select { |entry| entry["canEmbed"] }
    .each_with_object({}) do |entry, obj|
      obj[entry["layerId"]] = {
        layer: entry["leafletOsmId"],
        darkLayer: entry["leafletOsmDarkId"],
        apikey: entry["apikey"]
      }.compact
    end
end
```
But I'm no ruby expert

2025-03-16 19:10 UTC, closed without merging