Yatharths11/issue5258
openstreetmap/openstreetmap-website pull request #5361
Opened 2024-11-30 13:51 UTC by Yatharths11

### Description

### How has this been tested?

2024-11-30 14:27 UTC, tomhughes commented
Why would `highway=highway` be a bus way? It's a nonsense tag that has [no uses](https://taginfo.openstreetmap.org/tags/highway=highway#overview).

2024-12-03 09:52 UTC, hlfan requested changes

2024-12-03 09:52 UTC, hlfan commented on config/locales/en.yml
> +          highway: "Busway"
If you mean to resolve #5258, the key here should be busway.

2025-01-15 13:13 UTC, gravitystorm commented
Thank you @Yatharths11 for making your pull request to this project!

Unfortunately, as @hlfan has pointed out, it doesn't quite resolve the problem. You need to change your code, as he describes.

Please feel free to either reopen this PR when you have made the fix, or you could open a new PR instead.

2025-01-15 13:13 UTC, closed without merging